#!/usr/bin/env node
/* Builds the two deliverables from src/.

     fighter.html                the drop-in-anywhere page you deploy
     dist/fighter-artifact.html  the same page minus the document wrapper,
                                 which the Artifact host supplies itself

   The modules are plain scripts concatenated into one inline <script>, not ES
   modules: they share a single top-level scope, exactly as they did when this
   was one file. That keeps every declaration visible to every other module
   with no export bookkeeping, and keeps the shipped page free of module
   semantics. The price is that ORDER MATTERS — top-level const and let are not
   hoisted across files — so the manifest below is the load order, and adding a
   module means placing it deliberately rather than dropping it in a folder. */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "src");

/* Load order. Roughly: what the game is, then what it does, then how it is
   driven. Anything evaluated at load time must come after what it reads. */
const MODULES = [
  "config",      /* tunables, world constants, input bits, shared helpers   */
  "input",       /* bindings, saved settings, keyboard, gamepad, touch      */
  "rig",         /* poses and animation data                               */
  "hurtboxes",   /* what can be hit, per pose (generated)                  */
  "moves",       /* normal-move frame data                                 */
  "characters",  /* the roster: palettes, stats, specials                  */
  "font",        /* the 5x7 bitmap font                                    */
  "sprites",     /* pose rasteriser and its cache                          */
  "stages",      /* procedural backgrounds                                 */
  "fighter",     /* move registry, fighter state, move selection           */
  "game",        /* the simulation                                         */
  "audio",       /* synthesised sound                                      */
  "render",      /* everything drawn per frame                             */
  "ai",          /* the CPU opponent                                       */
  "net",         /* lockstep netcode                                       */
  "ui"           /* menus, scenes, the main loop, boot                     */
];

const BUNDLE_MARKER = "//__BUNDLE__";

const shell = readFileSync(resolve(SRC, "shell.html"), "utf8");
if (!shell.includes(BUNDLE_MARKER)){
  console.error("build: src/shell.html has no " + BUNDLE_MARKER + " marker");
  process.exit(1);
}
const NOTICE = "/* Generated by tools/build.mjs from src/ \u2014 do not edit this file directly. */";
const bundle = '"use strict";\n' + NOTICE + "\n" + MODULES
  .map(m => readFileSync(resolve(SRC, m + ".js"), "utf8").replace(/\n+$/, ""))
  .join("\n\n");

const page = shell.replace(BUNDLE_MARKER, bundle);

/* --check builds to memory and compares, so CI (and `npm test`) can prove the
   committed fighter.html still matches src/ instead of trusting that whoever
   last edited it remembered to rebuild. */
const CHECK = process.argv.includes("--check");
if (CHECK){
  let current = "";
  try { current = readFileSync(resolve(ROOT, "fighter.html"), "utf8"); } catch { /* absent */ }
  if (current !== page){
    console.error("build --check: fighter.html does not match src/.");
    console.error("  Either it was edited directly (edit the module in src/ instead),");
    console.error("  or src/ changed without a rebuild. Run: npm run build");
    process.exit(1);
  }
  console.log("build --check: fighter.html is up to date with src/ (" + MODULES.length + " modules)");
  process.exit(0);
}
writeFileSync(resolve(ROOT, "fighter.html"), page);

/* The Artifact host wraps the page in its own document, and rejects one that
   brings its own wrapper. */
const at = (marker) => {
  const i = page.indexOf(marker);
  if (i < 0){ console.error("build: could not find " + marker); process.exit(1); }
  return i;
};
const artifact =
  page.slice(at("<title>"), at("</style>") + "</style>".length) + "\n" +
  page.slice(at("<body>") + "<body>".length, at("</body>")).trim() + "\n";

const stray = ["<!doctype", "<html", "<head>", "<body>", "</html>"].filter(t => artifact.toLowerCase().includes(t));
if (stray.length){ console.error("build: wrapper tags survived the strip: " + stray.join(", ")); process.exit(1); }
if (!/<title>[^<]+<\/title>/.test(artifact)){ console.error("build: output has no <title>"); process.exit(1); }

mkdirSync(resolve(ROOT, "dist"), { recursive: true });
writeFileSync(resolve(ROOT, "dist/fighter-artifact.html"), artifact);

const version = (page.match(/GAME_VERSION\s*=\s*"([^"]+)"/) || [])[1] || "unknown";
const kb = n => (n / 1024).toFixed(1) + " KB";
console.log("build v" + version + " — " + MODULES.length + " modules");
console.log("  fighter.html                " + kb(page.length));
console.log("  dist/fighter-artifact.html  " + kb(artifact.length));
